version: "3.7"

services:
  postgreDB: 
    image: postgres
    container_name: postgres_ticketReservation
    ports:
      - 5432:5432
    volumes:
      - TicketReservation:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  TicketReservation: 
    name: ticketReservation